name: ASFHyP3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  # For documentation
  - mkdocs
  - mkdocs-material=6.2
  - mkdocs-material-extensions
  - hyp3_sdk=0.5.0  # also pinned in docs/using/sdk.md
  - asf_tools=0.2.0  # also pinned in docs/tools/asf_tools.md
  - pip:
      # For documentation
      - mkdocs-asf-theme>=0.2.1
      - mkdocs-section-index
      - mkdocstrings
      - git+https://github.com/Jlrine2/mkdocs-gitsnippet-plugin.git
