name: hyp3-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - 'python=3.10'
  - pip
  - hyp3_sdk=7.7.5  # also pinned in docs/using/sdk.md
  - asf_tools=0.8.4  # also pinned in docs/tools/asf_tools.md
  - pip:
    - -r requirements.txt
